### ISSUE TITLE
Console.log() QUESTION

### ISSUE THREAD

**Issue by drdexter33** [the-road-to-learn-react/hacker-stories#63]
On page 56 when discussing state, it's mentioned as an exercise in the book to add a console.log() to a couple of places in the code.

![image](https://github.com/the-road-to-learn-react/hacker-stories/assets/15314276/855c40cb-1695-42ae-b100-513cd516b4b2)

I am able to add a console.log('App Renders') in the app component:

![image](https://github.com/the-road-to-learn-react/hacker-stories/assets/15314276/6aa7ab16-55da-4c79-9305-4bdcdb1ad544)

And the Search component:

![image](https://github.com/the-road-to-learn-react/hacker-stories/assets/15314276/71a610f7-3d4f-41b1-ae3e-c3e23663feda)

But in the List component, I'm having trouble:

![image](https://github.com/the-road-to-learn-react/hacker-stories/assets/15314276/ae86759d-8684-486d-bccc-6e929f62ddef)

`      at JSXParserMixin.parseTopLevel (C:\Users\drdex\source\repos\react\RoadToReact\hacker-stories\node_modules\@babel\parser\lib\index.10:17:20 AM [vite] Internal server error: C:\Users\drdex\source\repos\react\RoadToReact\hacker-stories\src\App.jsx: Unexpected token, expected "," (58:29)`

Thanks..

doug

**Comment by rwieruch** [comment]
The List component has an implicit return, so you are not able to add a console logging there. It needs to be

```
const List = (props) => {
  console.log('List Renders');

  return (<ul>...</ul>);
}

**Comment by drdexter33** [comment]
Got it..
Thanks, it works!

**Comment by rwieruch** [comment]
Perfect :)
